import { selector } from "recoil";

export const productSelector = selector({       // TODO: hard coded right now 
    key: "productSelector",
    get: ({ get }) => {
        // async fetch products from products document
        return [
            {
                uuid: "1",
                name: "Makeup Revolution Maxi Reloaded Palette Large It Up, Multicolor, 60 g",
                primaryCategory: "Spray",
                ratingNumber: 3,
                reviewCount: 264,
                price: 1299,
                stockStatus: true,
                productImage: [
                    "https://m.media-amazon.com/images/I/91zfFbCp7eL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91XD5PkJVgL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91KeBvIAECL._AC_UL320_.jpg",
                ],
                tags: [
                    "cosmetics",
                    "makeup",
                    "lipstick",
                    "red",
                    "blue",
                    "mayblene",
                    "loreal",
                ],
            },
            {
                uuid: "2",
                name: "Makeup Revolution Maxi Reloaded Palette Large It Up, Multicolor, 60 g",
                primaryCategory: "Spray",
                ratingNumber: 4,
                reviewCount: 264,
                price: 1299,
                stockStatus: true,
                productImage: [
                    "https://m.media-amazon.com/images/I/51gxFVB9xvL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91XD5PkJVgL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91KeBvIAECL._AC_UL320_.jpg",
                ],
                tags: [
                    "cosmetics",
                    "makeup",
                    "lipstick",
                    "red",
                    "blue",
                    "mayblene",
                    "loreal",
                ],
            },
            {
                uuid: "3",
                name: "Makeup Revolution Maxi Reloaded Palette Large It Up, Multicolor, 60 g",
                primaryCategory: "Spray",
                ratingNumber: 4,
                reviewCount: 264,
                price: 1299,
                stockStatus: false,
                productImage: [
                    "https://m.media-amazon.com/images/I/61Df6Ww6DaL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91XD5PkJVgL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91KeBvIAECL._AC_UL320_.jpg",
                ],
                tags: [
                    "cosmetics",
                    "makeup",
                    "lipstick",
                    "red",
                    "blue",
                    "mayblene",
                    "loreal",
                ],
            },
            {
                uuid: "4",
                name: "Makeup Revolution Maxi Reloaded Palette Large It Up, Multicolor, 60 g",
                primaryCategory: "Spray",
                ratingNumber: 4,
                reviewCount: 264,
                price: 1299,
                stockStatus: true,
                productImage: [
                    "https://m.media-amazon.com/images/I/41OrDHmQLVL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91XD5PkJVgL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91KeBvIAECL._AC_UL320_.jpg",
                ],
                tags: [
                    "cosmetics",
                    "makeup",
                    "lipstick",
                    "red",
                    "blue",
                    "mayblene",
                    "loreal",
                ],
            },
            {
                uuid: "5",
                name: "Makeup Revolution Maxi Reloaded Palette Large It Up, Multicolor, 60 g",
                primaryCategory: "Spray",
                ratingNumber: 4,
                reviewCount: 264,
                price: 1299,
                stockStatus: true,
                productImage: [
                    "https://m.media-amazon.com/images/I/71nfJ8FSVjS._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91XD5PkJVgL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91KeBvIAECL._AC_UL320_.jpg",
                ],
                tags: [
                    "cosmetics",
                    "makeup",
                    "lipstick",
                    "red",
                    "blue",
                    "mayblene",
                    "loreal",
                ],
            },
            {
                uuid: "6",
                name: "Makeup Revolution Maxi Reloaded Palette Large It Up, Multicolor, 60 g",
                primaryCategory: "Spray",
                ratingNumber: 4,
                reviewCount: 264,
                price: 1299,
                stockStatus: true,
                productImage: [
                    "https://m.media-amazon.com/images/I/71BB5iXmBHL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91XD5PkJVgL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91KeBvIAECL._AC_UL320_.jpg",
                ],
                tags: [
                    "cosmetics",
                    "makeup",
                    "lipstick",
                    "red",
                    "blue",
                    "mayblene",
                    "loreal",
                ],
            },
            {
                uuid: "7",
                name: "Makeup Revolution Maxi Reloaded Palette Large It Up, Multicolor, 60 g",
                primaryCategory: "Spray",
                ratingNumber: 3,
                reviewCount: 264,
                price: 1299,
                stockStatus: true,
                productImage: [
                    "https://m.media-amazon.com/images/I/91zfFbCp7eL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91XD5PkJVgL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91KeBvIAECL._AC_UL320_.jpg",
                ],
                tags: [
                    "cosmetics",
                    "makeup",
                    "lipstick",
                    "red",
                    "blue",
                    "mayblene",
                    "loreal",
                ],
            },
            {
                uuid: "8",
                name: "Makeup Revolution Maxi Reloaded Palette Large It Up, Multicolor, 60 g",
                primaryCategory: "Spray",
                ratingNumber: 4,
                reviewCount: 264,
                price: 1299,
                stockStatus: true,
                productImage: [
                    "https://m.media-amazon.com/images/I/51gxFVB9xvL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91XD5PkJVgL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91KeBvIAECL._AC_UL320_.jpg",
                ],
                tags: [
                    "cosmetics",
                    "makeup",
                    "lipstick",
                    "red",
                    "blue",
                    "mayblene",
                    "loreal",
                ],
            },
            {
                uuid: "9",
                name: "Makeup Revolution Maxi Reloaded Palette Large It Up, Multicolor, 60 g",
                primaryCategory: "Spray",
                ratingNumber: 4,
                reviewCount: 264,
                price: 1299,
                stockStatus: false,
                productImage: [
                    "https://m.media-amazon.com/images/I/61Df6Ww6DaL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91XD5PkJVgL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91KeBvIAECL._AC_UL320_.jpg",
                ],
                tags: [
                    "cosmetics",
                    "makeup",
                    "lipstick",
                    "red",
                    "blue",
                    "mayblene",
                    "loreal",
                ],
            },
            {
                uuid: "10",
                name: "Makeup Revolution Maxi Reloaded Palette Large It Up, Multicolor, 60 g",
                primaryCategory: "Spray",
                ratingNumber: 4,
                reviewCount: 264,
                price: 1299,
                stockStatus: true,
                productImage: [
                    "https://m.media-amazon.com/images/I/41OrDHmQLVL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91XD5PkJVgL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91KeBvIAECL._AC_UL320_.jpg",
                ],
                tags: [
                    "cosmetics",
                    "makeup",
                    "lipstick",
                    "red",
                    "blue",
                    "mayblene",
                    "loreal",
                ],
            },
            {
                uuid: "11",
                name: "Makeup Revolution Maxi Reloaded Palette Large It Up, Multicolor, 60 g",
                primaryCategory: "Spray",
                ratingNumber: 4,
                reviewCount: 264,
                price: 1299,
                stockStatus: true,
                productImage: [
                    "https://m.media-amazon.com/images/I/71nfJ8FSVjS._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91XD5PkJVgL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91KeBvIAECL._AC_UL320_.jpg",
                ],
                tags: [
                    "cosmetics",
                    "makeup",
                    "lipstick",
                    "red",
                    "blue",
                    "mayblene",
                    "loreal",
                ],
            },
            {
                uuid: "12",
                name: "Makeup Revolution Maxi Reloaded Palette Large It Up, Multicolor, 60 g",
                primaryCategory: "Spray",
                ratingNumber: 4,
                reviewCount: 264,
                price: 1299,
                stockStatus: true,
                productImage: [
                    "https://m.media-amazon.com/images/I/71BB5iXmBHL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91XD5PkJVgL._AC_UL320_.jpg",
                    "https://m.media-amazon.com/images/I/91KeBvIAECL._AC_UL320_.jpg",
                ],
                tags: [
                    "cosmetics",
                    "makeup",
                    "lipstick",
                    "red",
                    "blue",
                    "mayblene",
                    "loreal",
                ],
            },
        ];
    },
});
